### ISSUE TITLE
Add support for SQLite as DB

### ISSUE THREAD

**Issue by psyciknz** [leepeuker/movary#168]
Topic says it all I guess.

This would be a docker install, essentiually for 1 user (me), I'd rather not stand up another dd.

I guess asking could mariadb be used as a fall back.

**Comment by leepeuker** [comment]
Hey, good idea, I will look into it.

**Comment by psyciknz** [comment]
Oh awesome....and am I correct, for docker if I use the Environment variable HTTP_PORT it will shift the site away from 80?  As I'm getting clash in my reverse proxy network

**Comment by leepeuker** [comment]
>  if I use the Environment variable HTTP_PORT it will shift the site away from 80?

If you use the `docker-compose.yml` inside the repository than yes, that will change the exposed port to the host, but this yml is primarily for development. 
In case you just want to use the app, have another look at the [install guide](https://github.com/leepeuker/movary#install-via-docker), you do not need to use `HTTP_PORT` (not used anywhere), you can just directly change the the part mapping (e.g. change `80:80` to `8080:80` if you want to expose port 8080)

**Comment by psyciknz** [comment]
Yeah I use docker caddy reverse proxy , which I’m uses a caddy network.  And so uses the internal port.  No worries, I got it going

**Comment by leepeuker** [comment]
Ups sorry for the close, still work in progress

**Comment by leepeuker** [comment]
See https://github.com/leepeuker/movary/releases/tag/0.35.0

Please report any errors. When background jobs are running I encountered a few lock errors, not sure how to fix this yet.
