### ISSUE TITLE
Add Jellyfin scrobbler

### ISSUE THREAD

**Issue by leepeuker** [leepeuker/movary#177]
Automatically sync Jellyfin watches to movary. 

If you are interested in this please add a thumbs up to this comment.

**Comment by Taubin** [comment]
I would love to have jellyfin syncing, I've replaced Plex after their servers went down one too many times and I couldn't watch my own media from the other room. Thank you so much for building this. Cheers

**Comment by Hukuma1** [comment]
Just found this project and did a control-f on Jellyfin. Glad to see someone posted about it!

**Comment by leepeuker** [comment]
Setup a repository for the plugin with a bit of basic setup: https://github.com/leepeuker/jellyfin-plugin-movary 

Development of the plugin will continue there (support appreciated, never worked with jellyfin before!).
