### ISSUE TITLE
Letterboxd import fails

### ISSUE THREAD

**Issue by bunkerman** [leepeuker/movary#195]
Taking the communication from https://www.reddit.com/r/movary/comments/zuu2xr/movary_docker_permissions/ to Github:

So the import fails with that logs:
"[2022-12-29T08:46:29.042878+00:00] movary.WARNING: Letterboxd import: Could not import movie by uri: https://boxd.it/15Jw {"exception":"[object] (Movary\\Api\\Tmdb\\Exception\\TmdbResourceNotFound(code: 0): No resource found: [https://api.themoviedb.org/3/movie/38559?api_key=x](https://api.themoviedb.org/3/movie/38559?api_key=344462d8f126f7e5939ded689c625341)xx at /app/src/Api/Tmdb/Exception/TmdbResourceNotFound.php:11)"} []

[2022-12-29T08:46:31.264193+00:00] movary.WARNING: Letterboxd import: Could not import movie by uri: https://boxd.it/6ncU {"exception":"[object] (Movary\\Api\\Tmdb\\Exception\\TmdbResourceNotFound(code: 0): No resource found: [https://api.themoviedb.org/3/movie/213781?api_key=x](https://api.themoviedb.org/3/movie/213781?api_key=344462d8f126f7e5939ded689c625341)xx at /app/src/Api/Tmdb/Exception/TmdbResourceNotFound.php:11)"} []

[2022-12-29T08:46:32.656572+00:00] movary.WARNING: Letterboxd import: Could not import movie by uri: https://boxd.it/eN4S {"exception":"[object] (Movary\\Api\\Tmdb\\Exception\\TmdbResourceNotFound(code: 0): No resource found: [https://api.themoviedb.org/3/movie/418772?api_key=x](https://api.themoviedb.org/3/movie/418772?api_key=344462d8f126f7e5939ded689c625341)xx at /app/src/Api/Tmdb/Exception/TmdbResourceNotFound.php:11)"} []

PHP Fatal error: Uncaught TypeError: Movary\Domain\Company\CompanyEntity::__construct(): Argument #3 ($originCountry) must be of type string, null given, called in /app/src/Domain/Company/CompanyEntity.php on line 21 and defined in /app/src/Domain/Company/CompanyEntity.php:7



Stack trace:

#0 /app/src/Domain/Company/CompanyEntity.php(21): Movary\Domain\Company\CompanyEntity->__construct(921, 'Next Wednesday ...', NULL, 6748)

#1 /app/src/Domain/Company/CompanyRepository.php(81): Movary\Domain\Company\CompanyEntity::createFromArray(Array)

#2 /app/src/Domain/Company/CompanyRepository.php(70): Movary\Domain\Company\CompanyRepository->fetchById(921)

#3 /app/src/Domain/Company/CompanyApi.php(34): Movary\Domain\Company\CompanyRepository->update(921, 'Next Wednesday ...', NULL)

#4 /app/src/Service/Tmdb/ProductionCompanyConverter.php(65): Movary\Domain\Company\CompanyApi->update(921, 'Next Wednesday ...', NULL)

#5 /app/src/Service/Tmdb/ProductionCompanyConverter.php(47): Movary\Service\Tmdb\ProductionCompanyConverter->fixUniqueConstraintViolation(Object(Movary\Domain\Company\CompanyEntity))

#6 /app/src/Service/Tmdb/ProductionCompanyConverter.php(27): Movary\Service\Tmdb\ProductionCompanyConverter->createMissingCompany(Object(Movary\Api\Tmdb\Dto\TmdbProductionCompany))

#7 /app/src/Service/Tmdb/SyncMovie.php(71): Movary\Service\Tmdb\ProductionCompanyConverter->getMovaryProductionCompaniesFromTmdbMovie(Object(Movary\Api\Tmdb\Dto\TmdbMovie))

#8 /app/src/Service/Letterboxd/LetterboxdMovieImporter.php(40): Movary\Service\Tmdb\SyncMovie->syncMovie(238215)

#9 /app/src/Service/Letterboxd/LetterboxdMovieImporter.php(25): Movary\Service\Letterboxd\LetterboxdMovieImporter->createMovie('https://boxd.it/...')

#10 /app/src/Service/Letterboxd/ImportHistory.php(107): Movary\Service\Letterboxd\LetterboxdMovieImporter->importMovieByLetterboxdUri('https://boxd.it/...')

#11 /app/src/Service/Letterboxd/ImportHistory.php(41): Movary\Service\Letterboxd\ImportHistory->getMovieFromCsvLineRecord('https://boxd.it/...')

#12 /app/src/Service/Letterboxd/ImportHistory.php(94): Movary\Service\Letterboxd\ImportHistory->execute(1, '/app/src/HttpCo...')

#13 /app/src/Service/JobProcessor.php(29): Movary\Service\Letterboxd\ImportHistory->executeJob(Object(Movary\JobQueue\JobEntity))

#14 /app/src/Command/ProcessJobs.php(84): Movary\Service\JobProcessor->processJob(Object(Movary\JobQueue\JobEntity))

#15 /app/src/Command/ProcessJobs.php(47): Movary\Command\ProcessJobs->processJob()

#16 /app/vendor/symfony/console/Command/Command.php(312): Movary\Command\ProcessJobs->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#17 /app/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#18 /app/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Movary\Command\ProcessJobs), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#19 /app/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#20 /app/bin/console.php(22): Symfony\Component\Console\Application->run()

#21 {main}

thrown in /app/src/Domain/Company/CompanyEntity.php on line 7"

![grafik](https://user-images.githubusercontent.com/7395381/209937720-019fabcd-2b48-43bd-bcdb-5023d81f1dcc.png)

**Comment by leepeuker** [comment]
Ah, I have to make the origin country of companies optional it seems, will fix this soon, thx for reporting.

**Comment by leepeuker** [comment]
Please update to the latest version [0.35.8](https://github.com/leepeuker/movary/releases/tag/0.35.8) and try again.

**Comment by bunkerman** [comment]
The watchlist import works, but the rating import is failing:

"...
[2022-12-30T08:58:51.664277+00:00] movary.INFO: Letterboxd import: Ignoring rating because movie already has one: Zoolander [] []
[2022-12-30T08:58:51.665078+00:00] movary.INFO: Letterboxd import: Ignoring rating because movie already has one: Gravity [] []
[2022-12-30T08:58:51.665917+00:00] movary.INFO: Letterboxd import: Ignoring rating because movie already has one: The Rum Diary [] []
[2022-12-30T08:58:51.666823+00:00] movary.INFO: Letterboxd import: Ignoring rating because movie already has one: Never Let Me Go [] []
[2022-12-30T08:58:51.709964+00:00] movary.ERROR: Could not process job. {"exception":"[object] (RuntimeException(code: 0): Invalid rating: 0 at /app/src/ValueObject/PersonalRating.php:14)"} []"

**Comment by leepeuker** [comment]
Hm while testing around I noticed that the whole history process does not work as expected. The `watched.csv` used for imports contains each movie only one time with the last watched date. If a movie was watched multiple times it cannot be imported like this. I am working on an update.

**Comment by leepeuker** [comment]
Please try to import (everything) again with the version [0.36.0](https://github.com/leepeuker/movary/releases/tag/0.36.0). Let me know how it goes :+1:

**Comment by bunkerman** [comment]
Nice, looks good!

![IMG_20221230_215049](https://user-images.githubusercontent.com/7395381/210111024-ea94b039-00f6-4553-8843-1aa195ded612.jpg)

I'll make an indepth check the next days.
