### ISSUE TITLE
Feature request: Public View

### ISSUE THREAD

**Issue by bunkerman** [leepeuker/movary#196]
Hi,

is it possible or on your feature list to implement a public view for visitors of users not logged in on a movary instance? Like letterboxd is doing it e.g. https://letterboxd.com/cspecialk/

**Comment by leepeuker** [comment]
Hey, this feature already exists! All urls starting with `/<username>/...` can be viewed publicly (check your `Privacy` type on the `/settings` page, must be set to `Visible to everyone`.
The url `/<username>`  itself does not exist currently, the "default" page for a user currently is `/<username>/dashboard`. We could add an internal redirect form username only to the dashboard url for easier discovery :thinking:

**Comment by bunkerman** [comment]
Oh cool, nice! Think I will be moving from letterboxd (and feeding rss to my wordpress) to movary :)
