### ISSUE TITLE
Document API endpoints

### ISSUE THREAD

**Issue by leepeuker** [leepeuker/movary#203]
Currently there is no straight forward documentation for the API endpoints Movary provides.

**Comment by JVT038** [comment]
Let's just use [OpenAPI](https://www.openapis.org/) for this.

I would like to see proper API endpoints implemented in `/api`, so that I could start experimenting with a native Android app :D

**Comment by leepeuker** [comment]
I agree. I will setup the basics, I already have something in mind.
