### ISSUE TITLE
Import Netflix CSV history files

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#219]
Netflix supports exporting the viewing history. It can be exported [here](https://www.netflix.com/viewingactivity).

A screenshot of a formatted example (my viewing history):

![image](https://user-images.githubusercontent.com/47184046/211395759-36787531-94fa-45b2-908c-975421c3821c.png)

It would be useful to be able to import this into Movary.

**Comment by leepeuker** [comment]
https://github.com/leepeuker/movary/releases/tag/0.42.0

**Comment by JVT038** [comment]
@leepeuker So I'm looking for the next thing to work on, and I'm considering importing the Plex watch history.
Is this OK with you? I don't know which direction you want this project to go to and what the 'roadmap' is to the stable release.

My idea:
After implementing the Plex import, I'll look to import Jellyfin history and maybe importing the [Emby](https://emby.media/) history as well.
Hopefully the API of Jellyfin doesn't differ _too_ much from the Emby API and we can literally just use the same code for both APIs. 
When this importing stuff is done, I would like to add support for TV shows and ultimately add a dark mode to every page.

**Comment by leepeuker** [comment]
The roadmap for V1 you can see here: https://github.com/leepeuker/movary/milestone/1
I will take time at the weekend to think about it again and make the tasks for v1 "final".

I am fine when you are working on the plex importer, that would have the highest prio of importers from my site.

I would say let us discuss the next step afterwards

**Comment by JVT038** [comment]
I would definitely add importing Jellyfin history to the v1 milestone.
There are a lot of people in the self-hosting community (your target audience) who use Jellyfin. So this feature would be very nice for a lot of people.

I'll start working on the Plex importer and create a draft once I have something.

**Comment by leepeuker** [comment]
I have created an issue for this topic https://github.com/leepeuker/movary/issues/272

For version 1.0 I want all currently known potential breaking changes and UX/UI changes (this includes things e.g. icon change) done. New features like jellyfin importer etc are not a requirement from my perspective but a nice to have for v1, I see no issue delivering this at a later point
