### ISSUE TITLE
Import watch history from Jellyfin

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#220]
It would be nice if Movary could import all 'played' items on Jellyfin.
This can be done using their API.
The documentation is [here](https://api.jellyfin.org/#tag/Items/operation/GetItems)

My idea:

The user creates an API key for Movary and supplies this to Movary using an environment variable (or something like that).
The user can then go to the settings and Movary can scan all the available users on the Jellyfin server. Movary obviously has access because of the API key.
The user selects their account on Jellyfin and Movary then queries all the played items with the userId from that user.
Movary then imports all those results from Jellyfin into the database.

**Comment by JVT038** [comment]
I would like to start discussing the implementation of a Jellyfin API client in Movary.
How would this work?

    To start off, where would the backend API code be located? Probably somewhere in the /src/Api/Jellyfin directory, but I've also seen some subdirectories like cache, dto, Exception and ValueObject and I'm not sure what those directories are for.
    So how would the Jellyfin API code be structured and where? Also, could @leepeuker add proper comments in the codebase with explanations for everything and/or a proper documentation that does the same? Would really help with my development, as I don't have to figure everything out myself.
    Second, what's up with the /src/Domain directory? Is that relevant for the Jellyfin API implementation? I don't think so, but I'm not sure, because I don't know what that directory is supposed to do.
    Third, we will probably have to add a job in src/JobQueue, where the Jellyfin server will be synced periodically. Or not?
    Fourth, do we want to use an API key or an authorization token? The Jellyfin API key would be the easiest to use, because then we just have to add the API key to the headers with every request. But this would also mean the normal non-admin users can't use the Jellyfin API, because they can't create an API key. In case we want to allow non-admin users to sync their Jellyfin libraries, we can use [/Users/AuthenticateByName](https://api.jellyfin.org/#operation/AuthenticateUserByName) to allow the user to supply their username and password and get an authentication token in return. This would require the Jellyfin server to have SSL, as the traffic would otherwise be left unencrypted and the sensitive data would be transferred publicly.

The beginning / basics of this implementation has to be rock solid, so that we don't have to do any refactorings later. We can later use this to sync Jellyfin items as 'watched' if it has been watched on Trakt / Netflix / any other platform. This way we could do two-way synchronisation.
But for now the goal will be to import all the watched items on Jellyfin.

Either way, how do you want to implement this? Any thoughts?

**Comment by pbogre** [comment]
do you think this will be addressed in the future? i would greatly appreciate this feature

**Comment by lee-peuker** [comment]
There was no plan, but I have no issue reopening this issue if you want it.

@JVT038 To address your old comment

- first: `Api/Jellyfin` is good, the code directly related to Jellyfin should be placed here, see the other api namespaces as examples
- second: the `Domain` namespace contains the basic domain elements of Movary itself, like `Movie` or `Person` etc. these classes are used to interact with Movary itself. 
- third: yes we need a job, an import should be processed independently
- fourth: we are using an authorization token for plex, so let us do the same for Jellyfin, so it is not only easier but consistent too

**Comment by leepeuker** [comment]
There was no plan, but I have no issue reopening this issue if you want it.

@JVT038 To address your old comment

- first: `Api/Jellyfin` is good, the code directly related to Jellyfin should be placed here, see the other api namespaces as examples
- second: the `Domain` namespace contains the basic domain elements of Movary itself, like `Movie` or `Person` etc. these classes are used to interact with Movary itself. 
- third: yes we need a job, an import should be processed independently
- fourth: we are using an authorization token for plex, so let us do the same for Jellyfin, so it is not only easier but consistent too

**Comment by leepeuker** [comment]
Jellyfin import was added. @pbogre You can test it with the nightly docker image. Please report if you have any issues :)

**Comment by pbogre** [comment]
just got the chance to try it out and it worked wonderfully when importing my watched library! great work!  :)
