### ISSUE TITLE
Allow registration so people can host public instances

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#234]
Add an environment variable that allows people to sign up in the login page. This variable would be `false` by default, but can manually be set to `true`.
So it would add a button that says 'register' and the user is able to create a new account.

**Comment by leepeuker** [comment]
I do not like the idea of a public registration **at the moment** for a few reasons:
- I have not focused on (and tested existing) security aspects much as of right now (at least not enough that I feel good about it)
- The user management tools are currently only rudimentary (some basic cli commands)
- There are no user roles (everyone has the same rights, e.g. everyone can delete all scheduled jobs)
- There is no mail supported integrated yet, which means we cannot send email verification or password resets
- probably more things I cannot think of right now

Sure we can disable registration by default and tell users to only activate it on there on risk, but giving the user the option at all opens him/her to too much potential risk factors and sends the wrong message about the state of movary in my opinion. 
 
That is way I cannot support this with good conscience right now, but we can definitely at this later when at least a few of my concerns mentioned are fixed.

**Comment by leepeuker** [comment]
So, we have user roles and user management UI now, the biggest blockers for user registration are gone for me. 
Still would like to have integrated email support first, but I guess we can let the user decide at this point

**Comment by JVT038** [comment]
I would choose a nice email PHP library and include that.
Please don't write an entire SMTP PHP client from scratch, because that would be a pain to maintain.

**Comment by leepeuker** [comment]
Definitely not :D I have used https://github.com/PHPMailer/PHPMailer in the past without any problems

**Comment by JVT038** [comment]
Yeah, good choice. I have experience with it as well :)

So, what do you want to use E-Mail for? Anything besides a password reset?
