### ISSUE TITLE
Add middleware to routes

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#235]
I think it would be a good improvement to add middlewares to the routes. 
Especially when the controller has to verify whether the user is logged in or not.
For example, this piece of code is repeated across a lot of different controllers:

```php
if ($this->authenticationService->isUserAuthenticated() === false) {
    return Response::createSeeOther('/');
}
```
Wouldn't it be better to handle this in a middleware class? 
I think it would be better to add a middleware to the routes and to check whether the user is logged in, in an auth middleware.
Also add a middleware for the login page that checks if the user is logged out. The login page shouldn't be able to be accessed when the user is logged in.
Furthermore, perhaps create a 'route group' so that one middleware can be specified to apply to multiple routes. This way we don't have to define the same middleware 10 times for 10 different routes, but can just say 'This middleware belongs to these 10 routes' once.

**Comment by JVT038** [comment]
I have looked through the code for a while now, and honestly can't comprehend what's going on, let alone add a middleware.
So could @leepeuker do this one?

**Comment by leepeuker** [comment]
Yes I am aware of this and will do it as soon as it gets to the top of my prio list.
