### ISSUE TITLE
Add support for more date formats

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#251]
I'm personally used to dd-mm-YYYY (like 27-01-2023), but some regions have others like YYYY-dd-mm. 
Adding support for more date formats would improve user experience.
Perhaps add a custom date format editor? That the user can literally type a date format like dd-mm-YYYY or something like that?

**Comment by leepeuker** [comment]
There already is support for 4 different date types, checkout the account setting page, or am I missing something?

**Comment by JVT038** [comment]
> Ah I think you want more possiblities than the four currently available, correct?

Yes

**Comment by leepeuker** [comment]
I am not sure how difficult it would be implement a custom date format editor and if it would be worth the effort (and worth the tech dept/bug potential coming with user definable custom inputs).
There should not be so many widely used date formats and even if we missed one (like for example `YYYY-dd-mm.`) we could simply just extend the current options with the missing one (should be just a few new lines).

**Comment by leepeuker** [comment]
I would close this issue for now with the results:
- no customizable date formats are planned (see my last comment why)
- if someone wants an additional date format we can add it to the available options
