### ISSUE TITLE
Add comment to each play

### ISSUE THREAD

**Issue by jv43** [leepeuker/movary#252]
It would be great if I can write something about each logged play. Like how I feel, whom I watched the movie with and where.
Thanks!

**Comment by leepeuker** [comment]
Was thinking about this already, just had no personal use case for it and was waiting to see if someone will request this feature. Should be relatively easy to implement.

**Comment by jv43** [comment]
> Was thinking about this already, just had no personal use case for it and was waiting to see if someone will request this feature. Should be relatively easy to implement.

Glad to hear that!

**Comment by leepeuker** [comment]
I have implemented comments for watch dates and not for specific plays, that would have been much more complicate and hopefully not necessary. Update to the new release [0.41.0](https://github.com/leepeuker/movary/releases/tag/0.41.0) to try it out. Does this work as you wanted it?

**Comment by jv43** [comment]
> I have implemented comments for watch dates and not for specific plays, that would have been much more complicate and hopefully not necessary. Update to the new release [0.41.0](https://github.com/leepeuker/movary/releases/tag/0.41.0) to try it out. Does this work as you wanted it?

Great! Downloaded the new image and tried it, adding and editing comments worked as expected. For displaying, I have an idea for you to consider:

On the movie detail page, it would be better if the comment could be shown somehow, e.g. when hovering the date list item by just adding a `title` attr, since the comment is already in the `data-comment` attr.

![Snipaste_2023-01-29_09-23-34](https://user-images.githubusercontent.com/15061046/215298915-3632912f-d335-43f4-8ca9-77fda571aaeb.jpg)

Or, directly in the list item itself:

![Snipaste_2023-01-29_09-31-04](https://user-images.githubusercontent.com/15061046/215299104-0db1feda-79e1-44f0-86e2-7b74683eea36.jpg)

**Comment by leepeuker** [comment]
Using tooltips does not work on mobile and displaying it after the date breaks the UI in my eyes, mabye we can add a notepad symbol or something like this at the right site of button to display that a comment is available :thinking:

**Comment by jv43** [comment]
> Using tooltips does not work on mobile and displaying it after the date breaks the UI in my eyes, mabye we can add a notepad symbol or something like this at the right site of button to display that a comment is available 🤔

I agree. Just add a notepad symbol would be enough for me. Minimum UI adjustment.

**Comment by leepeuker** [comment]
Icon to indicate comments on watch dates added  in [0.43.0](https://github.com/leepeuker/movary/releases/tag/0.43.0)
