### ISSUE TITLE
Install guide should be updated for tmdb image cache under Docker

### ISSUE THREAD

**Issue by jv43** [leepeuker/movary#253]
In the [guide](https://github.com/leepeuker/movary#install-with-docker-recommended), only /app/storage is mentioned. 
In order for tmdb image cache to work under docker, you need to persist the content of /app/public/storage too (I'm not sure if the directory differs if I change the Privacy settings.)

**Comment by leepeuker** [comment]
It is enough to bind `/app/storage` to a docker volume like the example shows. This includes the cached images (which are saved at `/app/storage/app/public/`). `/app/public/storage` is just a symbolic link  to `/app/storage/app/public/` and not a really directory.

**Comment by jv43** [comment]
> It is enough to bind `/app/storage` to a docker volume like the example shows. This includes the cached images (which are saved under `/app/storage/app/public/`). `/app/public/storage` is just a symbolic link to `/app/storage/app/public/` and not a real directory.

Got it. Thanks!
