### ISSUE TITLE
Use Plex API to import all the watched movies

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#264]
As the title says.
We can use their authentication system which is documented [here](https://forums.plex.tv/t/authenticating-with-plex/609370) to gain a token that allows us access to the user's library.
Then just scan all the items, link them to TMDB and import them.

**Comment by leepeuker** [comment]
Oh great idea!

**Comment by JVT038** [comment]
Plex needs an identifier string, which is a randomly generated string.
My idea: Just have the user generate a random string (`openssl rand -base64 32`) and add it to the environment variables.
This will be used as app identifier.
Additionally, should we let the user change the app name? Or have it hardcoded to 'Movary'?

**Comment by leepeuker** [comment]
We decided to not include a Plex importer directly into Movary, it would be to much logic to implement and maintain for a feature probably not needed in most cases and on a day to day basis.

This could be done e.g. in a separate application to split the scope of the projects.
