### ISSUE TITLE
Text unreadable in dark mode when Netflix item is not found on TMDB

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#286]
![image](https://user-images.githubusercontent.com/47184046/219900678-c4b897a8-9046-4c46-81f4-f596691d7e79.png)

The text in this screenshot is difficult to read when it is in dark mode.
Preferably, change the color to a darker color, like black.

**Comment by leepeuker** [comment]
Yes, and the rating edit icon on movie detail pages is barley visible in dark.

**Comment by JVT038** [comment]
![image](https://user-images.githubusercontent.com/47184046/220160385-20d7e767-2591-47a9-b79b-c1ad802edcb1.png)

The login page does not have dark mode.
I think it should have dark mode if the `theme` cookie is set to `dark`.

**Comment by leepeuker** [comment]
Rating icon and netflix import issues are fixed (thanks for the help @JVT038 )

The last release enabled the dark mode on the login page accidentally. The login page was not prepared for this and looks shitty in dark mode, I am working on improving this.
