### ISSUE TITLE
Build Docker containers with multi-arch support

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#296]
So the Docker image currently only supports amd64, but this means that people with a Raspberry Pi can't use Movary. (They have an arm processor architecture and need something like armv7 or armv8)
With [multi-arch](https://docs.docker.com/build/building/multi-platform/) support or multi-platform as it's officially called, we can easily build Movary for multiple processor architectures and provide support for more people. 

Github actions officially supports multi-arch building, with instructions [here](https://docs.docker.com/build/ci/github-actions/multi-platform/)

**Comment by leepeuker** [comment]
Added multi-arch support to main ticket https://github.com/leepeuker/movary/issues/206
