### ISSUE TITLE
Add 2FA (Two-Factor Authentication) with time-based code

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#319]

**Comment by leepeuker** [comment]
See my comment [here](https://github.com/leepeuker/movary/issues/320#issuecomment-1518635273) about security.

But I have never implement 2FA myself, so just for that reason alone I am very interested in this :smile:

**Comment by leepeuker** [comment]
I think we could use this lib: https://github.com/Spomky-Labs/otphp

The usage for TOTP seems simple in the [exmaples](https://github.com/Spomky-Labs/otphp/blob/11.3.x/doc/index.md)

Todos:
- [ ] add database column `2fa_secret` to user table
- [ ] add `Spomky-Labs/otphp` as composer dependcy
- [ ] add to user settings UI an option to enable 2FA and display secret and QR code (require password to confirm, maybe via modal?)
- [ ] look into the [custom parameters](https://github.com/Spomky-Labs/otphp/blob/11.3.x/doc/Customize.md), let us use what is useful
- [ ] add to user settings UI an option to disable active 2FA (require password to confirm)

We could rename the `Password` user settings page to `Security` and add the 2FA after the password section 🤔
