### ISSUE TITLE
Turn Movary into a PWA as a temporary solution for mobile phones

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#343]

**Comment by leepeuker** [comment]
Movary already is a PWA, it fill all requirements (here is the [manifest](https://github.com/leepeuker/movary/blob/main/public/manifest.json)). I have installed it via chrome and firefox on my android devices.
Do you see something missing?

**Comment by JVT038** [comment]
Oof, then I missed it lol.
I never tested it, I just assumed it wasn't a PWA.
