### ISSUE TITLE
Cannot get plex webhook url - empty field on screen?

### ISSUE THREAD

**Issue by axl7777** [leepeuker/movary#348]
![movary plex webhook](https://github.com/leepeuker/movary/assets/33523828/24c8d77a-cc6c-43b4-916a-7fb51b9ab745)

**Comment by leepeuker** [comment]
Your webhooks are inactive because there is no application url set. Checkout the latest [release notes](https://github.com/leepeuker/movary/releases/tag/0.52.0) how to fix this :)
