### ISSUE TITLE
Add nightly docker image

### ISSUE THREAD

**Issue by leepeuker** [leepeuker/movary#351]
Currently we publish docker images for each new release, tagged with the release number

We should add a `nightly` tag to docker with an image that gets recreated on every merge into main. This enables user to try the newest features/fixes without having to wait for a new release.

**Comment by tungbq** [comment]
Hi @leepeuker, do you need any help? Can I pick up this task?

**Comment by leepeuker** [comment]
Hey @tungbq, thanks for your offer! Help is always appreciated, you are welcome to look into it. You can look into the current workflow for creating the docker images on release as a starting point: https://github.com/leepeuker/movary/blob/main/.github/workflows/dockerhub-tag.yml

If you are fit with docker a really important task where we need help is: https://github.com/leepeuker/movary/issues/206

In case you want to communicate with us contributors directly you are welcome to join our chat at https://matrix.to/#/#movary-development:leepeuker.dev

**Comment by tungbq** [comment]
@leepeuker thanks for your promptly response and the reference to get started.
I've proposed new PR #362 for this task. Please have a look. Thanks!

**Comment by leepeuker** [comment]
It seems to work as expected: https://hub.docker.com/layers/leepeuker/movary/nightly/images/sha256-17268fb8273a64b7b6a9360027287c8189315401221637e7ace19163de079d17?context=explore

Thanks for the help @tungbq
