### ISSUE TITLE
Unable to use Movary after importing Netflix history

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#354]
After importing my Netflix history, I'm unable to use Movary, as it only shows a blank screen.
This error appears in the logs:
```
movary.EMERGENCY: Language code not handled: en {"exception":"[object] (RuntimeException(code: 0): Language code not handled: en at /app/src/Api/Tmdb/Cache/TmdbIso6931Cache.php:35)"} []
```

**Comment by leepeuker** [comment]
Could you pleas check the content of the database table `cache_tmdb_languages`? it should contain 187 rows, one of them should `en` + `English`. Is that the case for you?

**Comment by leepeuker** [comment]
I would love to know how you got a incomplete cache table here :thinking: Currently the cache is handled as either existing or not. If the cache is incomplete we have a problem, that is not a handled state. You can try to delete all rows from the table, it should load the cache again the next time you load the broken page and in theory fix the issue.

**Comment by JVT038** [comment]
I deleted all rows from that table and when visiting the page, it took ~3min to add 187 rows and now it's fixed.

**Comment by leepeuker** [comment]
Holy shit that is very slow 😯

**Comment by JVT038** [comment]
Yeah, and it confuses me, because all the other services on my NAS (which also require MySQL) run wayy faster than this.
I might try other databases (such as MariaDB), because this is just too annoying tbh.

**Comment by leepeuker** [comment]
For future problems the newly added cli commands can be used to prevent need for direct database access: https://github.com/leepeuker/movary/pull/365
