### ISSUE TITLE
Number of Unique Movies showing on Dashboard is less

### ISSUE THREAD

**Issue by muhammad-ans** [leepeuker/movary#372]
I have watched 607 movies and 635 total plays
But the unique movies showing are 597. 
The movies are there but count is not increasing.
In all movies there are 600 entries.
If I add movies from total lanuages it is 607.
In history section it shows 635 entries.
Movies are there just count for unique movies and in all movies is incorrect.

**Comment by muhammad-ans** [comment]
Yeah Sure
here is the csv 
[history.csv](https://github.com/leepeuker/movary/files/11601350/history.csv)
It must have 634 plays and 606 unique movies.

**Comment by muhammad-ans** [comment]
These are unique movies without any replay
[unique.csv](https://github.com/leepeuker/movary/files/11602509/unique.csv)

**Comment by leepeuker** [comment]
I have found and fixed the problem. Movies without any genres assigned to them where ignored in the calculation of the unique movie count. The fix will be part of the next release. Thanks again for reporting this

**Comment by leepeuker** [comment]
The fix is part of the release [0.53.1](https://github.com/leepeuker/movary/releases/tag/0.53.1)
