### ISSUE TITLE
Can't export Histroy.csv

### ISSUE THREAD

**Issue by TheBig-O** [leepeuker/movary#384]
I'm trying to migrate from SQLite to MySQL and consistently get an error when clicking the "export History.csv" button. The app shifts to the "/settings/account/export/csv/history" page with an error saying the page isn't working. Is there another way to either export the history or migrate from SQLite to MySQL?

Using: 
Version: 0.53.1 
Browser: Chrome

**Comment by leepeuker** [comment]
Hey @TheBig-O, thank you for reporting this! I can reproduce the bug. It works fine with MySQL, only SQLite is affected. 
There is currently no other way to migrate between database types quickly. We have an open [issue](https://github.com/leepeuker/movary/issues/360) related to this topic. 

I will fix the export bug either today or tomorrow, you have to wait for this at the moment to switch. Sorry for the inconvenience.

**Comment by TheBig-O** [comment]
Awesome! Thank you! I thought it might be something screwed up in my setup.
I'm much more comfortable with MySQL and was happy to see the option to use it as the database. Love the work you've done on this and can't wait to shift over to MySQL... Well, I guess I can wait a little while.

**Comment by leepeuker** [comment]
The bugfix is part of the new [0.54.0](https://github.com/leepeuker/movary/releases/tag/0.54.0). Thanks again for the bug report :1st_place_medal:

**Comment by TheBig-O** [comment]
Thank you for that. Tonight's project is shifting over to Mysql!

**Comment by leepeuker** [comment]
FYI After importing a csv you should run the CLI command `tmdb:movie:sync` (see [docs](https://docs.movary.org/features/tmdb-data/#movie-metadata)) to fetch the meta data of your movies, otherwise there is not much to see

**Comment by TheBig-O** [comment]
Thanks for the tip! I'm sure that would've been kicking my butt. 😂

**Comment by TheBig-O** [comment]
Everything is up and running just fine and it seems more reliable (container stays up). Thanks again!
