### ISSUE TITLE
Use append to response to minimize the amount of API requests

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#420]
### Description

TMDB apparently has a feature called [append to response](https://developer.themoviedb.org/docs/append-to-response) which can combine multiple API requests into one.

In the case of Movary, when adding a movie, various requests are made.
One request for the movie details and another one for the movie credits.
These requests can be combined like this: `https://api.themoviedb.org/3/movie/27205?append_to_response=credits&language=en-US`, resulting in a response where the credits are automatically included.
We should refactor the API calls to use this as whenever possible, so we reduce the amount of API requests and reduce the loading times.

### Desired Behavior

Use append to response instead of separate API requests

**Comment by leepeuker** [comment]
I found one case (movie details and credits endpoints) where we could utilize the append to response feature.
