### ISSUE TITLE
Set Jellyfin movie watched when play is added

### ISSUE THREAD

**Issue by leepeuker** [leepeuker/movary#439]
If I watch a movie in Plex, I want the movie to be set as watched in Jellyfin as well.

Workflow:
- movie is watched in Plex
- the play is added to Movary via Plex webhook
- Movary processes the new play and triggers job to sync play with Jellyfin
- the job processing will update the watch status in Jellyfin

Additional:
- a full sync (Movary to Jellyfin) option should be available

Notes:
- Jellyfin endpoint to mark item as played [here](https://api.jellyfin.org/#tag/Playstate/operation/MarkPlayedItem)

**Comment by pbogre** [comment]
to add to this, it would be nice to have the full sync option the other way around as well (Jellyfin to Movary), especially for a first-time setup (today i had to add each watched movie from jellyfin manually).

furthermore it may be a good idea to add an option which adds all unwatched movies in jellyfin to the movary watchlist.

**Comment by leepeuker** [comment]
Agreed, that is what https://github.com/leepeuker/movary/issues/220 is for. Should be reopened soon

**Comment by JVT038** [comment]
Currently working on this in #456

**Comment by leepeuker** [comment]
We need the jellyfin item id to update the watch status. I think we simplest thing for now is to use the tmdbId to match the jellyfin item id to a Movary movie id. But how can we do that?

As far as I see there is no Jellyfin endpoint to search directly via tmdb id. My proposal:
- we have a local cache of tmdbId to jellyfinItemIds
  - add new db table `user_jellyfin_cache`, with columns `jellyfinUserId`, `jellyfinItemId`, `tmdbId`, `lastPlayedDate`, jellyfinUserId is a foreign key on the matching users table column -> if a authentication is removed it automatically purges the cache with ON DELETE CASCADE and it cannot create cache entries for not existing jellyfinUserIds
- if we do not find a matching jellyfinItemId to the watched tmdbId in the cache we try to import the movies from jellyfin again
- if we still do not find the jellyfinItemId afterwards -> Jellyfin does not have the movie
- if we found it we can add use the jellyfinItemId to add/remove the latest watchDate

Problems:
- when only using tmdbIds from the local cache  we get no update in case the tmdbIds changed (hopefully that should be edge cases?)
- to get changes to the current cache, we have to recheck all jellyfin items every time if we want to be up to date (expensive)
  - I found no way to sort the movies by last change date or something like that. so that we not process unchanged movies since the last check

Current URL used to fetch all items paginated: https://jellyfin.leepeuker.dev/Users/0f36492707ae4bfeaa03a8a16119e178/Items?Recursive=True&IncludeItemTypes=Movie&hasTmdbId=true&filters=IsNotFolder&fields=ProviderIds,DateLastRefreshed&limit=500&StartIndex=0

**Comment by JVT038** [comment]
> when only using tmdbIds from the local cache we get no update in case the tmdbIds changed 

According to [this](https://www.themoviedb.org/talk/5963ae4ac3a36828a1110612) thread, the TMDB ID never, ever changes. So this should never happen.

> I found no way to sort the movies by last change date or something like that. so that we not process unchanged movies since the last check

This is possible, the jellyfin web UI does this. The key `sortBy` is used to determine what you want to sort on (so you can use `dateCreated` or something) and `sortOrder` can be used if you want to sort `ascending` (so the oldest item first) or `descending` (so the neweset item first).

[More info](https://api.jellyfin.org/#tag/Items/operation/GetItemsByUserId)

What I'm worrying about is the fact that the `jellyfin_server_url` can be different per user. Not all users necessarily use the same Jellyfin server, which is why you should probably add `jellyfin_server_id` (or `jellyfin_server_url`) to the cache table, so you can distinguish the different Jellyfin items from the different Jellyfin servers. It can also occur that different servers have the same movies.

**Comment by leepeuker** [comment]
> TMDB ID never, ever changes. So this should never happen.

I meant changing when the jellyfin movie is rematched to another tmdb id because it was matched not correctly before or something like that.

> This is possible, the jellyfin web UI does this. The key sortBy is used to determine what you want to sort on (so you can use dateCreated or something) and sortOrder can be used if you want to sort ascending (so the oldest item first) or descending (so the neweset item first).

I know that you can sort, but I did not find any field I can use for sorting. there is no dateUpated or at least I could not find it :(

> What I'm worrying about is the fact that the jellyfin_server_url can be different per user.

Good point! I have replaced the jellyfinUserId column with the movary user id. This way the matching is always unique to the user and as long as a user can only have one server there should be no conflicts.

**Comment by JVT038** [comment]
I think you then just have to do a full re-sync every 24 hours or something like that.
