### ISSUE TITLE
Better documentation on what `JELLFIN_DEVICE_ID` refers to

### ISSUE THREAD

**Issue by tommitytom** [leepeuker/movary#474]
### Description

I'm setting up Jellyfin integration and I'm unsure what `JELLFIN_DEVICE_ID` refers to

### Desired Behavior

More precise documentation of what this value should be set to

**Comment by leepeuker** [comment]
The device id is used by Jellyfin to identify a unique client, so it can separate the clients (and there authentication tokens). 

Example:
If you have two Movary instances running and use the same `JELLFIN_DEVICE_ID` for both, removing the authentication from one of them would automatically invalidate the authentication of the other one.

In principle you can use anything as a device id (as far as I know), for example the string `1`. But the simpler it is the higher risk it could not be unique.

I will update the docs with an example how to generate a device id, it is basically the same as written at `PLEX_IDENTIFIER` which serves the same purpose as `JELLFIN_DEVICE_ID` but for Plex.

**Comment by tommitytom** [comment]
Great, thanks for the info!
