### ISSUE TITLE
Sort watchlist w.r.t release date

### ISSUE THREAD

**Issue by muhammad-ans** [leepeuker/movary#475]
### Description

Provide an option to sort with release date on watchlist page.

### Desired Behavior

With this feature we could sort movies with release date. In the current scenario released and unreleased movies are mixed and I think sorting with release date would be  a good idea.

**Comment by leepeuker** [comment]
I will add advanced search option to the watchlist, similiar to how they are implemented on the "All movies" page

**Comment by leepeuker** [comment]
done, will be part of the next release

![image](https://github.com/leepeuker/movary/assets/19872901/73a425ef-440b-459b-b159-33a96b049411)
