### ISSUE TITLE
Add option to sync only movies that have never been synced before

### ISSUE THREAD

**Issue by sahinakkaya** [leepeuker/movary#476]
### Description

Currently `imdb:sync` command can only sync according to 3 options:
- `--hours`: Number of hours required to have elapsed since last sync
- `--threshold`: Maximum number of movies to sync
- `--movieIds`: Comma separated string of movie ids to force sync for

### Desired Behavior

I suggest adding a fourth option something like:
`--never-synced`: Sync only movies that have never been synced

### Additional Context

I always want to see IMDB ratings in movie details page. The feature I described would be unnecessary for me if #131 was implemented. But if that one has a long time come, I think an option like this might work for people like me.

**Comment by leepeuker** [comment]
In https://github.com/leepeuker/movary/issues/131 we want to sync the basic tmdb data (like release year, tagline, description), this does not include imdb. Fetching the tmdb data is much faster and safer than the html scraping we have to do to get the imdb rating, so I would not like to add this as an default option on data imports.

Adding a flag to only sync movies which have never been synced before sounds like a good idea and should not be difficult to add.

**Comment by sahinakkaya** [comment]
I just realized #131 was not about IMDB rating, sorry about that. My thought was syncing the IMDB rating when movie is added manually like you said. Either this or `--never-synced` option would be very nice.

**Comment by sahinakkaya** [comment]
I don't know how you handle html scraping but maybe you can use a 3rd party library like https://github.com/tboothman/imdbphp. Because syncing the imdb score operation is very slow, maybe 3rd party libraries could handle it better 🤔

**Comment by leepeuker** [comment]
The issue is not the html scraping performance but the time the request takes to fetch html from imdb. For example, I measured the execution time right now on my PC, it takes 1,5 - 2,5 seconds to fetch the data from imdb and ~0.0006 to extract the rating. So there is not much we can improve here as far as I see sadly :shrug: On the opposite even, if we are to fast imdb will rate limit us.

**Comment by leepeuker** [comment]
`--never-synced` flag was added and will be part of the next release (or use the nightly image to immediately use it)

**Comment by sahinakkaya** [comment]
Thank you very much!
