### ISSUE TITLE
Mark movies watched without a play date

### ISSUE THREAD

**Issue by leepeuker** [leepeuker/movary#485]
Currently you cannot mark a movie as watched without having to add a play date. This is an problem if you do not know or want to add a play date but still want to mark the movie as watched.

**Comment by muhammad-ans** [comment]
For some movies one don't remember the date but month and year and for some one don't remember the the date and month but the year. So, If we could add the date as only year or month-year that would be awesome.

**Comment by leepeuker** [comment]
yes good point @muhammad-ans , let us keep that in mind while working on this topic. I like the idea but I am not sure how expensive the implementation of that is :thinking:

**Comment by muhammad-ans** [comment]
SQL permits to store the month or day as 00 in database.

**Comment by leepeuker** [comment]
A date is no longer required when adding plays for a movie. Movies without dates will not be part of a users history page.
