### ISSUE TITLE
Add RottenTomatoes Tomatometer Score

### ISSUE THREAD

**Issue by muhammad-ans** [leepeuker/movary#499]
### Description

It would add tomatometer score on the movie page.

### Desired Behavior

Just Like IMDB the tomatometer score would be displayed on the movie page.

**Comment by leepeuker** [comment]
I wanted to do this before, but sadly there is no API to get the tomatometer score from and no reliable way to find the rottentomatoes url of a movie to scrape the the rating via html. 

If you or anyone else find a solution for this I will look into this again, but as long as there are no new ideas this does not seem possible to implement.

**Comment by muhammad-ans** [comment]
What about https://omdbapi.com/
It does provide rotten tomatoes critics score through imdb id.

**Comment by leepeuker** [comment]
> What about https://omdbapi.com/ It does provide rotten tomatoes critics score through imdb id.

I thought this is a premium only service bit just noticed that they offer 1000 free daily requests which is not bad. But the missing ssl makes the service a bit suspicious to me and I am not sure about the quality of data theirs users provide :thinking: Maybe worth a look, but has to be evaluated
