### ISSUE TITLE
Cannot add some movies

### ISSUE THREAD

**Issue by SirMartin** [leepeuker/movary#511]
### Description

I found an issue adding some fails, it returns a 500 error, and looking in the logs of the container I found this.

`[php-fpm:access] 127.0.0.1 -  28/Sep/2023:16:09:45 +0200 "GET /index.php?tmdbId=96581" 200 /app/public/index.php 7.809 2048 0.00%
[2023-09-28T16:09:48.837893+02:00] movary.EMERGENCY: No company found by id: 135193 {"exception":"[object] (RuntimeException(code: 0): No company found by id: 135193 at /app/src/Domain/Company/CompanyRepository.php:74)"} []`

I made an script to move all my ratings from TMDB to Movary, and from over 2000 ratings, I got issue with these 8 TMDB ids: `96581,  8980,  818, 180,  1913, 8874, 2770, 95932`

### Version

0.58.0

### Steps to Reproduce

1. Click on _Add Movie_ button.
2. Search for example for _Makinavaja_ (select the 1992 film) or _Mortadelo_ (in this case choose the 2003 film).
3. Select the movie
4. Enter a rating
5. Click on add play
6. An error appears

### Screenshots

![image](https://github.com/leepeuker/movary/assets/854646/f880221c-f495-47e0-a823-a8a1c298856e)

### Logs

```shell
[php-fpm:access] 127.0.0.1 -  28/Sep/2023:16:09:45 +0200 "GET /index.php?tmdbId=96581" 200 /app/public/index.php 7.809 2048 0.00%
[2023-09-28T16:09:48.837893+02:00] movary.EMERGENCY: No company found by id: 135193 {"exception":"[object] (RuntimeException(code: 0): No company found by id: 135193 at /app/src/Domain/Company/CompanyRepository.php:74)"} []
```

### Server OS

Debian

### Client Platform

None

### Client OS

Windows, Linux, Android

### Client Browser

Brave

**Comment by leepeuker** [comment]
Thanks for reporting, I think already know what I have to do to fix this. 

I would love to see the script you wrote to move your tmdb ratings, maybe we could add this as a feature or just share it directly for people with a similar use case :)

**Comment by leepeuker** [comment]
Hm okay sadly my initial idea did not prove correct. Could you please provide the log with the whole stack trace? You have to set `LOG_ENABLE_STACKTRACE=1` in your env to enable this. Additionally setting `LOG_LEVEL=debug` would maybe provide some useful context.

**Comment by SirMartin** [comment]
I'll do it right now, and add it to the thread.

Can you reproduce it?

The script is too crappy right now, but of course, it was my first idea trying to integrate, so if you can help me how and where. I would try to do it. I would try to improve my actual version, so can be automated (right now, I am getting some things hardcoded), and share it with you, so we can integrate it into Movary, it would be awesome.

**Comment by SirMartin** [comment]
Here it is, I added the 2 envvars, and start and reproduce the bug, and here it is the whole log.
[_movary_logs.txt](https://github.com/leepeuker/movary/files/12762287/_movary_logs.txt)

**Comment by leepeuker** [comment]
> Can you reproduce it?

No I cannot, I think you probably have a local state which does not match the data on tmdb anymore and Movary does not know how to handle this, at least we had an issue like this before.

Thank you very much for the stack trace, that should enable me to fix the issue. 

> I would try to improve my actual version, so can be automated (right now, I am getting some things hardcoded), and share it with you, so we can integrate it into Movary, it would be awesome.

Take your time and I am looking forward to it :)

**Comment by SirMartin** [comment]
Great, one of the problems is that right now I am entering the movies into Movary via `log-movie` because I couldn't find any option on the available API.

**Comment by SirMartin** [comment]
I saw it, but I didn't want to wait to use your amazing work 🤣
________________________________
De:Lee Peuker ***@***.***>
Enviado:viernes, 29 de septiembre de 2023 14:56
Para:leepeuker/movary
Cc: Eduardo; Author 
Asunto: Re: [leepeuker/movary] Cannot add some movies (Issue #511)

An API endpoint for this should come soon, see this issue, it is at least on the list for my next todos :D

**Comment by SirMartin** [comment]
Looking both companies films, probably are the same company but for some reason is not the same on tmdb. But sounds good about removing the requirement.

**Comment by leepeuker** [comment]
Fix will be part of the next release, you can try it out already with the nightly docker image.

**Comment by SirMartin** [comment]
I have not time, but I just updated I tested it, and works perfectly. Thanks for your amagin work!

**Comment by SirMartin** [comment]
Hi @leepeuker , it took some time, but finally I had some time and rewrite and make a bit more user friendly the script I talked about for importing to movary from TMDB. I created in a repo, and make some instructions for it, just in case you want to add to Movary's README.

If you are interested into integrate it self on Movary, we can talk about, or feel free to use as much code as you can, is it on Node, so not sure how easy it will be move it to PHP, but I removed the usage of external libraries, so it will be easier.

Here is the link: https://github.com/SirMartin/TMDBToMovary

**Comment by leepeuker** [comment]
Awesome, thank you! I have created a follow up issue [here](https://github.com/leepeuker/movary/issues/544) to import the tmdb ratings.

**Comment by SirMartin** [comment]
Maybe you can add the info in the README until you finish the wizard way :smile:

**Comment by leepeuker** [comment]
Good idea, I have added a section to the docs [here](https://github.com/leepeuker/movary/commit/f9407a606ade5c449cbbb0f257a704ac06740007) :+1:
