### ISSUE TITLE
Search in persons does not work

### ISSUE THREAD

**Issue by muhammad-ans** [leepeuker/movary#515]
### Description

When you try to search a director,actor or actress it does not search, just reloads the page.

### Version

Nightly

### Steps to Reproduce

1. Go to Directors,actor or actress page 
2. type a name 
3. click on search icon
4. page refreshes

### Client Platform

None

**Comment by leepeuker** [comment]
Oh wow, thanks for reporting. The search button for the advanced search works. Maybe we broke the normal search when we added the advanced search.

I will try to fix it this weekend.

**Comment by leepeuker** [comment]
Fixed, will be part of the next release
