### ISSUE TITLE
Display Character name in the cast of Movie

### ISSUE THREAD

**Issue by muhammad-ans** [leepeuker/movary#519]
### Description

Currently only actor's name is shown on the movies.
Add the name of the character he played. 

### Desired Behavior

In the cast card add the role of actor 
like Robert De Niro as Jimmy Conway (In case of goodfellas)

**Comment by leepeuker** [comment]
Added character names:
![image](https://github.com/leepeuker/movary/assets/19872901/735b25a0-36a1-43a5-ac14-b9203e899ee7)

Character name can be disabled in the general user settings:
![image](https://github.com/leepeuker/movary/assets/19872901/65bf0e2e-ca18-4e1d-9c81-9dd771e1553a)

@muhammad-ans You can check it out with the nightly image or wait until the next release
