### ISSUE TITLE
Add link to Person's Imdb or Tmdb profile

### ISSUE THREAD

**Issue by muhammad-ans** [leepeuker/movary#520]
### Description

Adding button that takes you to tmdb or imdb page of a person would be nice just like this button is present in movie page so we could check further details on it.

### Desired Behavior

N/A

**Comment by leepeuker** [comment]
Summary of the changes I made:
- added imbdId for local persons (resync your tmdb person data to get the imdId)
- always display links to tmbd and imdb pages via icons on movie and person pages if possible (see screenshots)
- movie pages additionally display the ratings if exist

![image](https://github.com/leepeuker/movary/assets/19872901/12418fd1-c0b5-4288-9347-b6cdb8129f30)
![image](https://github.com/leepeuker/movary/assets/19872901/50368f2c-5a83-409a-9e46-2c79ae773ab6)
