### ISSUE TITLE
Add manage buttons to person page 

### ISSUE THREAD

**Issue by leepeuker** [leepeuker/movary#524]
A user on the person page should be able to:
- [ ] Refresh the person tmdb data
- [ ] Hide the person from top lists (more [here](https://github.com/leepeuker/movary/issues/505))

Design:
Let us reuse the `more` button and modal from the movie page for peoples

**Comment by JVT038** [comment]
Should we also add the ability to manually edit the person's data (so in case the TMDB data is incomplete and the user / admin can add person information themselves)

**Comment by leepeuker** [comment]
True, but I would see editing the person as a separate issue, this should be solved separately

**Comment by leepeuker** [comment]
Added new more button to person pages:
![image](https://github.com/leepeuker/movary/assets/19872901/6878a46e-ae44-40e6-ae44-0ac7c1e78001)

With these options:
![image](https://github.com/leepeuker/movary/assets/19872901/79a76fbd-218b-44dd-aaa8-f2b0a7652432)
