### ISSUE TITLE
Use the same photo in person list and detail pages after sync

### ISSUE THREAD

**Issue by sahinakkaya** [leepeuker/movary#538]
### Description

When I do `docker exec movary php bin/console.php tmdb:person:sync`, all the person information including the photos are synced as expected. But the photos in the person list page and person detail page are not same. I think this is a bug.

### Version

Nightly

### Steps to Reproduce

-

### Screenshots

![image](https://github.com/leepeuker/movary/assets/32161460/11d34ad4-fff6-4f4e-b915-2c3040b101b5)
![image](https://github.com/leepeuker/movary/assets/32161460/080da3fa-ce8f-49ba-b6f9-35ff9e968f1e)

### Client Platform

None

**Comment by sahinakkaya** [comment]
I am using Firefox 118.0.2, I force reloaded by holding Shift and clicking the reload button. Still same. I also tried a different browser from my phone which I never signed in and it is still showing different photos. So it is probably not about browser cache.

**Comment by sahinakkaya** [comment]
By the way, this doesn't bother me at all. I like watching movies and this project makes it even more fun. It is a great project! I just wanted to report the issue here so we know about it. This is great job @leepeuker, I really appreciate the efforts :)

**Comment by sahinakkaya** [comment]
I am not sure but this might be happening because `TMDB_ENABLE_IMAGE_CACHING: 1` in docker compose file. I recently set it to 0 and I don't experience this issue now.

**Comment by leepeuker** [comment]
Okay, so I found what caused this. On the dashboard we are using the cached version of person images, but on the person page we have hardcoded to use the tmdb image directly. I think we simply forgot to update this place when we added the image caching, so I will adjust this and double check that all places in the frontend are using cached images consistently.
