### ISSUE TITLE
Show movies from both watch history and watch list in person detail page

### ISSUE THREAD

**Issue by sahinakkaya** [leepeuker/movary#543]
### Description

Let's say I want to watch a movie from my watch list, but I can't decide what to watch. What I do is prioritize watching movies starring my favorite actor. If I'm lucky, I can remember which movie my favorite actor is in or I can see it from the movie cover. But in cases where I'm unlucky, I have to open the movies on my watch list and check who's starring which is very tedious (considering that I have to click 2 times in order to go to movie detail page in `/watchlist` page).

### Desired Behavior

When we go to the actor's page, we see which of the movies from our watch history he starred in. Similarly, it would be really nice if it could be seen which of the movies from our watch list he is starring. This way, I can choose an actor and when I went to his page, I can easily see his movies that I had not seen before and were on my watch list.

**Comment by sahinakkaya** [comment]
Maybe something like this could be made: 
![image](https://github.com/leepeuker/movary/assets/32161460/8f3b6714-aa90-47bc-aea8-6284a5b83bd6)

I actually like to implement this kind of basic things myself but I couldn't setup the development environment. If someone tell me the simplest way to setup the dev environment with docker, I can implement this feature. (this is also what I would prefer because as it can be seen from my previous issues, I like using this app and I would be more than happy to contribute :)

**Comment by leepeuker** [comment]
> I actually like to implement this kind of basic things myself but I couldn't setup the development environment. If someone tell me the simplest way to setup the dev environment with docker, I can implement this feature.

Checkout the docs on how to setup a local development environment [here](https://docs.movary.org/development/setup/) if you have not already. If you have problems or some things are not clear, ideally post into the Discord development channel, we are always glad to help :)
