### ISSUE TITLE
Make the watch date optional

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#556]
### Description

I have watched some movies, but I don't know when I watched it. 

### Desired Behavior

I would like to add a checkbox, which disables the watch date input. If the watch date is disabled, the recorded play will be shown in the UI with a watch date of 'unknown' (or something like that)

**Comment by leepeuker** [comment]
Hm, I think we have this already? 

![image](https://github.com/leepeuker/movary/assets/19872901/29d64879-abd0-47ce-a45c-709c0c48ffff)

![image](https://github.com/leepeuker/movary/assets/19872901/a5de79e4-41b4-4693-a2b8-b321488bd545)

**Comment by leepeuker** [comment]
Oh but during testing it I notices that setting watch date to empty is broken with sqlite, I will fix this

**Comment by JVT038** [comment]
Really? Well, in that case the issue can be closed lol; I didn't know it was already implemented

**Comment by leepeuker** [comment]
Was part of this release: https://github.com/leepeuker/movary/releases/tag/0.58.0
