### ISSUE TITLE
User data is not deleted when a user is removed

### ISSUE THREAD

**Issue by muhammad-ans** [leepeuker/movary#557]
### Description

If we create a 2nd user and delete it the watched data would be still there and would be assigned to the next user created as id of 2nd user would assigned to new user.

### Version

nightly

### Steps to Reproduce

1. Create a 2nd user.
2. add some movies as watched
3. delete the user
4. create new user
5. Deleted users history would be assigned to new user.

### Server OS

Fedora Silverblue 39

### Client Platform

None

**Comment by leepeuker** [comment]
Which database are you using?

**Comment by leepeuker** [comment]
I assume you are using SQLite, I just noticed that the foreign key support was not enabled, so the automatic cleanup of orphaned data entries was not happing. This should now be fixed

**Comment by muhammad-ans** [comment]
Yes, was using sqlite.
