### ISSUE TITLE
REQ: about languages and Time zone

### ISSUE THREAD

**Issue by punkyard** [leepeuker/movary#569]
### Description

hi
I can see in Settings/App the the time zone is fixed to Europe/Berlin
I couldn't change the language

### Desired Behavior

Could it be possible to update the TZ from the user interface?
Is the option to change language hidden somewhere? Do you need help to translate?

### Additional Context

bravo for that app - I've just found it and gave it a spin - it's awesome

**Comment by punkyard** [comment]
i've tried to set TZ in environment of my yaml:
`PHP_DATE_TIMEZONE: "${TIMEZONE}"`
but didn't work out

**Comment by leepeuker** [comment]
Oh yes, I think I never really tested changing my default time zone. I will test and fix potential issues.

**Comment by leepeuker** [comment]
There is currently no option to change to the UI language. We could add translations, this feature was not really requested yet. But it would talk time away from other tasks, I am not sure how high the interest in translation is.

**Comment by leepeuker** [comment]
Have a look at the [docs](https://docs.movary.org/configuration/), you can set the `TIMEZONE` env variable to update the timezone. `PHP_DATE_TIMEZONE` is only used during development.

I will add an option to adjust this in the settings UI as well.

**Comment by leepeuker** [comment]
Please create a separate issue for the translation feature request if we should follow this up

**Comment by punkyard** [comment]
thanks a lot the the update
+ the links to the doc have been useful to update my yaml file ✌️
