### ISSUE TITLE
REQ: change main page title

### ISSUE THREAD

**Issue by punkyard** [leepeuker/movary#570]
### Description

at the top left, it reads MOVARY

### Desired Behavior

could it be possible to edit this through admin interface?
we'd give it the name of our movie fan tam

### Additional Context

movary credits could be moved to the center bottom of the page - as it is regular to see ..

cheers

**Comment by leepeuker** [comment]
Changing the brand should be easy to implement, I will look into it.

> movary credits could be moved to the center bottom of the page - as it is regular to see ..

I am not really sure what you means with this? Which Movary credits do you want to move from where?

**Comment by leepeuker** [comment]
Added new option `Application Name` to the `Server` -> `General` settings page. 

![image](https://github.com/leepeuker/movary/assets/19872901/50514aa8-b0d7-4f0e-9011-ee882488f253)

Application name will be displayed as the navbar brand (as seen in the screenshot) name and as page title on the login page.

**Comment by punkyard** [comment]
Movary at the bottom of the page, as woth github for instance

![D3171043-9747-4BEF-98DE-ACAA9419CD9B](https://github.com/leepeuker/movary/assets/59349105/89b8abdd-b60f-4d44-ab2c-0bb04a1e9e50)

**Comment by leepeuker** [comment]
Hm I see. And how would the navbar look like when the logo/name is moved to the bottom?

**Comment by punkyard** [comment]
i think that's a different subject.
my topic here is the name.

is it possible to change to name Movary by our organisation name in the top bar. and eventually move the name of the app Movary, to the bottom of the page.
