### ISSUE TITLE
[Bug] Can't log in after upgrading to 1815eb87 from a367d204

### ISSUE THREAD

**Issue by Davilarek** [leepeuker/movary#600]
### Description

After upgrading to 1815eb87 from a367d204, I'm unable to log into my main account.
The login page just refreshes.
After using network tab of DevTools I was able to find a failing request to token auth.

### Version

Commit 1815eb87

### Steps to Reproduce

1. Upgrade to 1815eb8 from a367d204
2. Migrate
3. Try to log in
4. See unable to do so
5. Check out browser console and network tab
6. Observe error

### Screenshots

![obraz](https://github.com/leepeuker/movary/assets/62715937/1de44ed2-53bc-4961-b642-b51a54cdaafc)
Failed request
![obraz](https://github.com/leepeuker/movary/assets/62715937/f4f48ea6-bbd4-41a0-8fcd-9d98d1bedfcf)

### Logs

```shell
Warning: session_destroy(): Trying to destroy uninitialized session in /home/davil/AUR/movary/src/Util/SessionWrapper.php on line 32

Warning: session_regenerate_id(): Session ID cannot be regenerated when there is no active session in /home/davil/AUR/movary/src/Util/SessionWrapper.php on line 33

Warning: session_start(): Session cannot be started after headers have already been sent in /home/davil/AUR/movary/src/Util/SessionWrapper.php on line 53

Warning: Cannot modify header information - headers already sent by (output started at /home/davil/AUR/movary/src/Util/SessionWrapper.php:32) in /home/davil/AUR/movary/src/Domain/User/Service/Authentication.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /home/davil/AUR/movary/src/Util/SessionWrapper.php:32) in /home/davil/AUR/movary/public/index.php on line 65

Warning: Cannot modify header information - headers already sent by (output started at /home/davil/AUR/movary/src/Util/SessionWrapper.php:32) in /home/davil/AUR/movary/public/index.php on line 67
{"authToken":"<REDACTED>","user":{"id":1,"name":"Davilarek","isAdmin":true}}
```

### Server OS

Arch Linux

### Client Platform

Desktop

### Client OS

Arch Linux

### Client Browser

Firefox

**Comment by leepeuker** [comment]
Hey, thanks for reporting your issue.

Could you please try again with the lastest main branch ([1815eb8](https://github.com/leepeuker/movary/commit/1815eb87729ff693929741e0a2adc87d2dbcf8d8)) and verify if the issue persists?

**Comment by Davilarek** [comment]
What do you mean?
In the issue I mentioned I upgraded from a367d20 to latest (1815eb8)

**Comment by leepeuker** [comment]
Oh my bad, you are right, seems like I missed something there :+1:

**Comment by Davilarek** [comment]
![obraz](https://github.com/leepeuker/movary/assets/62715937/eff4be29-7062-400d-b959-459a92739e26)
`src/Service/Router/RouterService.php` is unmodified.

**Comment by leepeuker** [comment]
@Davilarek Sorry it seems like I forgot about this issue. Is this still happening/relevant?

**Comment by Davilarek** [comment]
Correct

**Comment by Davilarek** [comment]
Also this may be useful:
![obraz](https://github.com/leepeuker/movary/assets/62715937/5a05f9a2-b443-4e04-80f1-42a4bf12c83d)
It's one of the error-making requests' header.

**Comment by leepeuker** [comment]
Thank you @Davilarek for providing a fix 🏅
